//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceAltamira.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GET_TRIBUTOS
    {
        public Nullable<int> PK_ACTIVO { get; set; }
        public string Periodicidad_IBI { get; set; }
        public Nullable<decimal> IMP_IBI { get; set; }
        public string Periodicidad_Alcantarillado { get; set; }
        public Nullable<decimal> IMP_Alcantarillado { get; set; }
        public string Periodicidad_Basura { get; set; }
        public Nullable<decimal> IMP_Basura { get; set; }
        public string Periodicidad_Vado { get; set; }
        public Nullable<decimal> IMP_Vado { get; set; }
        public Nullable<decimal> Total_imp_otros { get; set; }
        public string periodicidad_otros { get; set; }
        public Nullable<int> ID_INMUEBLE { get; set; }
        public int PK_Activo1 { get; set; }
    }
}