//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceAltamira.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GET_COMUNIDADES
    {
        public Nullable<int> PK_ACTIVO { get; set; }
        public Nullable<decimal> IMP_TOTAL_CUOTA { get; set; }
        public string Periodicidad_Cuota { get; set; }
        public Nullable<decimal> IMP_TOTAL_DERRAMA { get; set; }
        public string Periodicidad_Derrama { get; set; }
        public Nullable<int> ID_INMUEBLE { get; set; }
        public int PK_Activo1 { get; set; }
    }
}