//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceAltamira.DATA
{
    
    public partial class vwReferenciasIC2
    {
        public int IDINMUEBLE { get; set; }
        public string ESTANDAR { get; set; }
        public string ALTERNATIVA { get; set; }
    }
}